\echo 'Starting database initialization...'

\ir 'Tables/user_history.sql'
\ir 'Tables/platform_stock_history.sql'
\ir 'Tables/market_candle_history.sql'
\ir 'Tables/watchlist_history.sql'
\ir 'Tables/watchlist_item_history.sql'
\ir 'Tables/api_key_history.sql'
\ir 'Tables/alert_history.sql'
\ir 'Tables/portfolio_history.sql'
\ir 'Tables/holding_history.sql'
\ir 'Tables/automated_trade_rule_history.sql'
\ir 'Tables/transaction_history.sql'
\ir 'Tables/log_history.sql'
\ir 'Tables/error_log_history.sql'
\ir 'Tables/admin_history.sql'

\ir 'Tables/user.sql'
\ir 'Tables/platform_stock.sql'
\ir 'Tables/market_candle.sql'
\ir 'Tables/watchlist.sql'
\ir 'Tables/watchlist_item.sql'
\ir 'Tables/api_key.sql'
\ir 'Tables/alert.sql'
\ir 'Tables/portfolio.sql'
\ir 'Tables/holding.sql'
\ir 'Tables/automated_trade_rule.sql'
\ir 'Tables/transaction.sql'
\ir 'Tables/log.sql'
\ir 'Tables/error_log.sql'
\ir 'Tables/admin.sql'

\echo 'Database initialization completed.'