CREATE TABLE automated_trade_rule_history (
    automated_trade_rule_history_id INT GENERATED ALWAYS AS IDENTITY (START WITH 785) PRIMARY KEY,
    rule_id INT NOT NULL,
    user_id INT NOT NULL,
    portfolio_id INT NOT NULL,
    platform_stock_id INT NOT NULL,
    condition_type VARCHAR(50) NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    quantity DECIMAL(18, 8) NOT NULL,
    threshold_value DECIMAL(18, 8) NOT NULL,
	quantity_type VARCHAR(50) NOT NULL, 
    date_created TIMESTAMP NOT NULL,
    audit_created_by VARCHAR(255) NOT NULL,
    audit_created_date TIMESTAMP NOT NULL,
    audit_updated_by VARCHAR(255),
    audit_updated_date TIMESTAMP,
    audit_version_number INT NOT NULL,
    history_dml_type CHAR(1) NOT NULL CHECK (history_dml_type IN ('i', 'u', 'd')),
    history_logged_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
